apiVersion: v1
kind: ConfigMap
metadata:
  name: services-metadata
  namespace: argocd
data:
  services.json: |
    {
        "obsv-metrics": {
            "team": "tm-reliability",
            "domain": "dm-dev-enablement",
            "system": "observability",
            "criticality": 3
            
        },
        "payment-service": {
        "team": "payments",
        "domain": "finance"
        },
        "user-service": {
        "team": "identity",
        "domain": "auth"
        },
        "notification-service": {
        "team": "communications",
        "domain": "messaging"
        }
    }

